- name: Gather facts about a Server Hardware by name
  oneview_server_hardware_facts:
#    config:  "{{ config }}"
    name: "{{ Serv_b3 }}"
  delegate_to: localhost
- set_fact: Serv_Bay_ip="{{ server_hardwares[0].mpHostInfo.mpIpAddresses[1].address }}"

- name: Ensure the server is registered in ICsp
  hpe_icsp_server:
    icsp_host: "{{ ICSP_Host }}"
    username: "{{ ICSP_Username }}"
    password: "{{ ICSP_Password }}"
    server_ipAddress: "{{ Serv_Bay_ip }}"
    server_username: "{{ ilo_Username }}"
    server_password: "{{ ilo_Password }}"
    state: present
  delegate_to: localhost
