- name: Create a Network Set
  oneview_network_set:
#    config: "{{ config }}"
    state: present
    data:
      name: "{{ NET_Set_One }}"
      networkUris: #From this point on, choose the networks needed (Ethernet)
        - "{{ Cust_VLAN }}"

- name: Create a Network Set
  oneview_network_set:
#    config: "{{ config }}"
    state: present
    data:
      name: "{{ NET_Set_Two }}"
      networkUris: #From this point on, choose the networks needed (Ethernet)
        - "{{ DMZ_VLAN }}"
        - "{{ Man_VLAN }}"
