- name: Gather facts about all Storage Pools
  oneview_storage_pool_facts:
#    config: "{{ config }}"
    name: "{{ Vol_Stor_Pool5 }}"
- set_fact: Vol_Stor_Pool1_uri="{{ storage_pools[0].uri }}"

- name: Gather facts about all Storage Systems
  oneview_storage_system_facts:
#    config: "{{ config }}"
  delegate_to: localhost
- set_fact: Vol_Stor_Sys_Uri="{{ storage_systems[0].uri }}"

- name: Create a Storage Volume Template
  oneview_storage_volume_template:
#    config: "{{ config }}"
    state: present
    data:
        name: "{{ Vol_Name_1 }}"
        state: "Configured"
        description: "{{ Vol_Tem_Description }}"
        provisioning:
             shareable: true
             provisionType: "Thin"
             capacity: "{{ c20Gb }}"
             storagePoolUri: "{{ Vol_Stor_Pool1_uri }}"
        stateReason: "None"
        storageSystemUri: "{{ Vol_Stor_Sys }}"
        snapshotPoolUri: "{{ Vol_Stor_Pool1_uri }}"
        type: StorageVolumeTemplateV3
  delegate_to: localhost
