- name: Create Ethernet network for VLAN DMZ
  oneview_ethernet_network:
#    config: '{{ config }}'
    state: present
    data:
      name: '{{ Net_Eth_Name }}'
      vlanId: '201'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500
