- name: Gather facts about '{{ Subnet_Name }}' IPV4 Subnet
  oneview_id_pools_ipv4_subnet_facts:
    config: "{{ config }}"
    name: "{{ Subnet_Name }}"

- set_fact: subnet_uri="{{ id_pools_ipv4_subnets[0].uri }}"
- debug: var=subnet_uri

- name: Create '{{ NET_Eth_Name }}' Ethernet network to associate to a Subnet
  oneview_ethernet_network:
    config: '{{ config }}'
    state: present
    data:
      name: "{{ NET_Eth_Name }}"
      vlanId: '201'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500
      subnetUri: "{{ subnet_uri }}"
