- name: Gather facts about all Server Hardwares
  oneview_server_hardware_facts:
#    config: "{{ config }}"
  delegate_to: localhost
- debug: var=server_hardwares

- name: Gather facts about a Server Hardware by name
  oneview_server_hardware_facts:
#    config:  "{{ config }}"
    name: "{{ Serv_b5 }}"
  delegate_to: localhost

- debug: var=server_hardwares
