- name: Gather facts about a Managed SAN by name
  oneview_managed_san_facts:
#    config: "{{ config }}"
    name: "{{ SAN_A }}"
  delegate_to: localhost
- set_fact: San_A_uri="{{ managed_sans[0].uri }}"

- name: Gather facts about a Managed SAN by name
  oneview_managed_san_facts:
#    config: "{{ config }}"
    name: "{{ SAN_B }}"
  delegate_to: localhost
- set_fact: San_B_uri="{{ managed_sans[0].uri }}"

- name: Create Fibre Channel network
  oneview_fc_network:
#    config: '{{ config }}'
    state: present
    data:
      name: '{{ NET_SAN_A }}'
      fabricType: 'FabricAttach'
      linkStabilityTime: '30'
      autoLoginRedistribution: true
      managedSanUri: '{{ SAN_A_Uri }}'

- name: Create Fibre Channel network
  oneview_fc_network:
#    config: '{{ config }}'
    state: present
    data:
      name: '{{ NET_SAN_B }}'
      fabricType: 'FabricAttach'
      linkStabilityTime: '30'
      autoLoginRedistribution: true
      managedSanUri: '{{ SAN_B_Uri }}'
