- name: Gather facts about VLAN DMZ Network
  oneview_ethernet_network_facts:
#    config: "{{ config }}"
    name: "{{ Man_VLAN }}"

- set_fact: NET_VLANMan_Uri="{{ ethernet_networks[0].uri }}"

- name: Create an ESXi 6.5 profile
  oneview_server_profile:
#    config: "{{ config }}"
    state: present
    data:
      name: "{{ Prof_Name }}"
      description: "{{ Prof_Description }}"
      server_hardware: "{{ Serv_b2 }}"
      serverHardwareTypeName: "{{ Serv_Type660 }}"
      enclosureGroupName: "{{ Enclosure_Group }}"
#
# This function of code is for the image streamer. If not needed, remove
#
      osDeploymentSettings:
        osDeploymentPlanName: "Zoly - deploy esxi 6.5"
        osCustomAttributes:
          -  name: Hostname
             value: "esxi01"
          -  name: DomainName
             value: dbpoc.uk
          -  name: ManagementNIC.connectionid
             value: 2
          -  name: ManagementNIC.dhcp
             value: false
          -  name: ManagementNIC.ipv4disable
             value: false
          -  name: ManagementNIC.networkuri
             value: "{{ NET_VLANMan_Uri }}"
          -  name: ManagementNIC.constraint
             value: "userspecified"
          -  name: ManagementNIC.dns1
             value: "{{ IP_Dns1 }}"
          -  name: ManagementNIC.dns2
             value: "{{ IP_Dns2 }}"
          -  name: ManagementNIC.netmask
             value: "{{ IP_SubNet }}"
          -  name: ManagementNIC.ipaddress
             value: "{{ IP_Address }}"
          -  name: ManagementNIC.gateway
             value: "{{ IP_Gateway }}"
#
# Boot mode is requred
#
      bootMode:
        manageMode: True
        mode: "UEFI"
#
# Next is the BIOS. If BIOS is needed, managebios needs to be True otherwise do not put the code in...default is false. The over-ridden settings are the items changed from the default
#
      bios:
        manageBios: "true"
        overriddenSettings:
          - id: "PowerRegulator"
            value: "StaticHighPerf"
          - id: "MinProcIdlePkgState"
            value: "NoState"
          - id: "MinProcIdlePower"
            value: "NoCStates"
          - id: "PowerProfile"
            value: "MaxPerf"
          - id: "IntelQpiPowerManagement"
            value: "Disabled"
          - id: "EnergyPerfBias"
            value: "MaxPerf"
          - id: "VirtualInstallDisk"
            value: "Enabled"
#
# Network connections. FC are required for the SAN storages. The two lines of code commented out are there if the mezzamine has more than 4 ports
#
      connections:
        - id: 1
          name: "{{ Deploy_NET }}"
          functionType: "Ethernet"
          portId: "Mezz 3:1-a"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ Deploy_NET }}"
          boot:
            priority: "Primary" #used as it is an iSCSi network
        - id: 2
          name: "{{ Man_VLAN }}"
          functionType: "Ethernet"
          portId: "Mezz 3:2-a"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ Man_VLAN }}"
          boot:
            priority: "NotBootable"
        - id: 3
          name: "{{ Man_VLAN_B }}"
          functionType: "Ethernet"
#          portId: "Mezz 6:1-a"
          portId: "Auto"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ Man_VLAN }}"
          boot:
            priority: "NotBootable"
        - id: 4
          name: "{{ Cust_VLAN }}"
          functionType: "Ethernet"
#          portId: "Mezz 6:2-a"
          portId: "Auto"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ Cust_VLAN }}"
          boot:
            priority: "NotBootable"
        - id: 5
          name: "{{ Cust_VLAN_B }}"
          functionType: "Ethernet"
          portId: "Mezz 3:1-c"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ Cust_VLAN }}"
          boot:
            priority: "NotBootable"
        - id: 6
          name: "{{ NET_SAN_A }}"
          functionType: "FibreChannel"
          portId: "Mezz 3:1-b"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ NET_SAN_A }}"
          boot:
            priority: "NotBootable"
        - id: 7
          name: "{{ NET_SAN_B }}"
          functionType: "FibreChannel"
          portId: "Mezz 3:2-b"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ NET_SAN_B }}"
          boot:
            priority: "NotBootable"
#
#SAN Storage. The LUN starts at 0 with increments of 1. the names are important, its what the SAN was labelled as in Volumes.
#
      sanStorage:
        hostOSType: 'VMware (ESXi)'
        manageSanStorage: true
        volumeAttachments:
          - id: 1
            volumeName: "{{ Vol_Name_1 }}"
            volumeStoragePoolName: "{{ Vol_Stor_Pool5 }}"
            volumeStorageSystemName: "{{ Vol_Stor_Sys }}"
            lunType: "Auto"
            lun: 0
            storagePaths:
              - isEnabled: true
                connectionId: 6 #SAN-A
                storageTargetType: 'Auto'
              - isEnabled: true
                connectionId: 7 #SAN-B
                storageTargetType: 'Auto'
          - id: 2
            volumeName: "{{ Vol_Name_2 }}"
            volumeStoragePoolName: "{{ Vol_Stor_Pool5 }}"
            volumeStorageSystemName: "{{ Vol_Stor_Sys }}"
            lunType: "Auto"
            lun: 1
            storagePaths:
              - isEnabled: true
                connectionId: 6 #SAN-A
                storageTargetType: 'Auto'
              - isEnabled: true
                connectionId: 7 #SAN-B
                storageTargetType: 'Auto'
#
# Now to power on the server in which the profile is on
#
- name: Power On the server hardware
  oneview_server_hardware:
#    config: "{{ config }}"
    state: power_state_set
    data:
        name : "{{ Serv_b4 }}" #The Server HW name
        powerStateData:
            powerState: "On"
            powerControl: "MomentaryPress" #MomentaryPress and PressAndHold are the two options
  delegate_to: localhost
