- name: Gather facts about a Server Profile Template by name
  oneview_server_profile_template_facts:
#    config: "{{ config }}"
    name: "{{ Prof_Tem_Name }}"
  delegate_to: localhost

- debug: var=server_profile_templates
